{{- if .Values.canary.cloudwatch.albArnSuffix }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.node.name }}-canary-analysis
  labels:
    app: {{ .Values.node.name }}
spec:
  args:
    - name: app
    - name: alb-arn-suffix
  metrics:
    - name: error-rate
      interval: 1m
      count: 3
      successCondition: result[0] <= 1
      failureCondition: result[0] > 5
      provider:
        cloudWatch:
          interval: 1m
          metricDataQueries:
            - id: errors
              metricStat:
                metric:
                  namespace: AWS/ApplicationELB
                  metricName: HTTPCode_Target_5XX_Count
                  dimensions:
                    - name: LoadBalancer
                      value: "{{`{{ args.alb-arn-suffix }}`}}"
                period: 60
                stat: Sum
                unit: Count
            - id: requests
              metricStat:
                metric:
                  namespace: AWS/ApplicationELB
                  metricName: RequestCount
                  dimensions:
                    - name: LoadBalancer
                      value: "{{`{{ args.alb-arn-suffix }}`}}"
                period: 60
                stat: Sum
                unit: Count
            - id: error_rate
              expression: "IF(requests > 0, errors / requests * 100, 0)"
              returnData: true

    - name: p95-latency
      interval: 1m
      count: 3
      successCondition: result[0] < 0.3
      failureCondition: result[0] > 0.5
      provider:
        cloudWatch:
          interval: 1m
          metricDataQueries:
            - id: p95_latency
              metricStat:
                metric:
                  namespace: AWS/ApplicationELB
                  metricName: TargetResponseTime
                  dimensions:
                    - name: LoadBalancer
                      value: "{{`{{ args.alb-arn-suffix }}`}}"
                period: 60
                stat: p95
              returnData: true
{{- end }}
