{{- if .Values.argocd.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.argocd.name }}
  namespace: {{ .Values.argocd.nameSpace }}
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: shared-alb         # same group for sharing ALB:contentReference[oaicite:3]{index=3}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:955967371588:certificate/58f46507-48af-4497-a836-43fb56b6b351
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.argocd.domainname }}
    alb.ingress.kubernetes.io/group.order: "10"


spec:
  rules:
  - host: {{ .Values.argocd.domainname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80
{{- end }}
