{{- if .Values.externalSecrets.clusterSecretStore.create }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.clusterSecretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.clusterSecretStore.serviceAccountName }}
            namespace: {{ .Values.externalSecrets.clusterSecretStore.serviceAccountNamespace }}
{{- end }}
