apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.node.name }}
  labels:
    app: node
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: {{ .Values.node.image }}
          ports:
            - containerPort: {{ .Values.node.port }}
          env:
            - name: REDIS_HOST
              value: {{ ternary .Values.redis.external.host .Values.redis.name .Values.redis.external.enabled | quote }}
            - name: REDIS_PORT
              value: {{ ternary .Values.redis.external.port .Values.redis.port .Values.redis.external.enabled | quote }}
            - name: REDIS_URL
              value: {{ ternary (printf "%s://%s:%v" .Values.redis.external.scheme .Values.redis.external.host .Values.redis.external.port) (printf "%s://%s:%v" .Values.redis.scheme .Values.redis.name .Values.redis.port) .Values.redis.external.enabled | quote }}
{{- if .Values.db.enabled }}
            - name: DB_HOST
{{- if .Values.db.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.hostKey | quote }}
{{- else }}
              value: {{ .Values.db.host | quote }}
{{- end }}
            - name: DB_PORT
{{- if .Values.db.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.portKey | quote }}
{{- else }}
              value: {{ .Values.db.port | quote }}
{{- end }}
            - name: DB_NAME
{{- if .Values.db.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.nameKey | quote }}
{{- else }}
              value: {{ .Values.db.name | quote }}
{{- end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.userKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.passwordKey | quote }}
            - name: DB_SSL
{{- if .Values.db.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName | quote }}
                  key: {{ .Values.db.sslKey | quote }}
{{- else }}
              value: {{ ternary "true" "false" .Values.db.ssl | quote }}
{{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        {{- if .Values.canary.cloudwatch.albArnSuffix }}
        - analysis:
            templates:
              - templateName: {{ .Values.node.name }}-canary-analysis
            args:
              - name: app
                value: {{ .Values.node.name | quote }}
              - name: alb-arn-suffix
                value: {{ .Values.canary.cloudwatch.albArnSuffix | quote }}
        {{- end }}
        - pause: { duration: 30s }
        - setWeight: 50
        {{- if .Values.canary.cloudwatch.albArnSuffix }}
        - analysis:
            templates:
              - templateName: {{ .Values.node.name }}-canary-analysis
            args:
              - name: app
                value: {{ .Values.node.name | quote }}
              - name: alb-arn-suffix
                value: {{ .Values.canary.cloudwatch.albArnSuffix | quote }}
        {{- end }}
        - pause: { duration: 30s }
        - setWeight: 100
