apiVersion: v1
entries:
  nginx-node-redis-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-03T18:26:05.11491573Z"
    description: A nodejs + redis application with nginx ingress controller using
      Helm.
    digest: 2f9f1af70b3085808f13d9662bc6e31c611cc0929a140b4f57817a5abdfad483
    name: nginx-node-redis-helm-chart
    type: application
    urls:
    - https://sajil143pb.github.io/Helm/nginx-node-redis-helm-chart-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-03T18:26:05.114660623Z"
    description: A nodejs + redis application with nginx ingress controller using
      Helm.
    digest: 4b8763a74185c368b2caaf05aed0c00b07850180ffbbbce38d252b5514308327
    name: nginx-node-redis-helm-chart
    type: application
    urls:
    - https://sajil143pb.github.io/Helm/nginx-node-redis-helm-chart-0.1.0.tgz
    version: 0.1.0
  nodeapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-03T18:26:05.115349712Z"
    description: A Helm chart for Kubernetes
    digest: 2ed5c64de86028614441299ec1708949c03b65b838393a1f2fb379b59510c233
    name: nodeapp
    type: application
    urls:
    - https://sajil143pb.github.io/Helm/nodeapp-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-03T18:26:05.114303806Z"
