apiVersion: v1
entries:
  nodeapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-05-28T12:41:00.815038+05:30"
    description: A Helm chart for Node application as Backend and Nginx as Frontend.
    digest: 209d7f8707d56839da9d75cc91f8d6e62c95fed94edb425400bf7d445ca2310a
    name: nodeapp
    type: application
    urls:
    - https://sajilpb.github.io/ibs-gitops-platform/nodeapp-1.0.10.tgz
    version: 1.0.10
generated: "2026-05-28T12:41:00.814736+05:30"
