namespaceOverride: nodeapp-production

node:
  enabled: true
  name: node
  image: ghcr.io/sajilpb/ibs-gitops-platform:8b14bdb8088f3d7c4fe8162729b55521cc6c2d48
  port: 5000
  targetPort: 5000
  replicaCount: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

redis:
  enabled: false
  name: redis
  image: redis:latest
  port: 6379
  replicaCount: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  external:
    enabled: true
    host: "rediscache-nodeapp-prod-j03vpl.serverless.use1.cache.amazonaws.com"
    port: 6379
    scheme: rediss

db:
  enabled: true
  host: ""
  port: 5432
  name: ""
  secretName: "nodeapp-db-secret"
  userKey: username
  passwordKey: password
  hostKey: host
  portKey: port
  nameKey: name
  sslKey: ssl
  ssl: true

externalSecrets:
  enabled: true
  awsSecretName: "nodeapp-db-credentials-v3"
  refreshInterval: 1h
  clusterSecretStore:
    create: true
    name: aws-secrets-manager
    region: us-east-1
    serviceAccountName: external-secrets
    serviceAccountNamespace: external-secrets

nginx:
  name: nginx
  image: nginx:latest
  port: 80
  servicePort: 80
  targetPort: 80
  replicaCount: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.order: "20"
    external-dns.alpha.kubernetes.io/hostname: prod.sajil.click
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:955967371588:certificate/58f46507-48af-4497-a836-43fb56b6b351
  hosts:
    - host: prod.sajil.click
      paths:
        - path: /
          pathType: Prefix
  tls: []

argocd:
  enabled: true
  name: argocd
  namespace: argocd
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: shared-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:955967371588:certificate/58f46507-48af-4497-a836-43fb56b6b351
      external-dns.alpha.kubernetes.io/hostname: argocd.sajil.click
      alb.ingress.kubernetes.io/group.order: "10"
    hosts:
      - host: argocd.sajil.click
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
    tls: []
