namespaceOverride: nodeapp-production

node:
  enabled: true
  name: node
  image: ghcr.io/sajilpb/ibs-gitops-platform:main
  port: 5000
  targetPort: 5000
  replicaCount: 2
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

redis:
  enabled: false
  name: redis
  image: redis:latest
  port: 6379
  replicaCount: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  external:
    enabled: true
    host: "rediscache-nodeapp-prod-j03vpl.serverless.use1.cache.amazonaws.com"
    port: 6379
    scheme: redis

nginx:
  name: nginx
  image: nginx:latest
  port: 80
  servicePort: 80
  targetPort: 80
  replicaCount: 2
  type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.order: "20"
    external-dns.alpha.kubernetes.io/hostname: prod.sajil.click
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:955967371588:certificate/58f46507-48af-4497-a836-43fb56b6b351
  hosts:
    - host: prod.sajil.click
      paths:
        - path: /
          pathType: Prefix
  tls: []

argocd:
  enabled: false
