name: Deploy Helm chart

on:
  push:
    paths:
      - '.github/workflows/Helmchart.yml'
      - 'helm/charts/**'
      - 'helm/docs/index.yaml'
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  pages: write       #  required for Pages deploy
  id-token: write    #  required for Pages authentication

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkoutrepository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Prepare
        run: mkdir -p helm/docs

      - name: Package
        run: |
          helm package helm/charts/* --destination helm/docs

      - name: Generate index.yaml
        run: |
          helm repo index helm/docs \
            --url https://sajilpb.github.io/ibs-gitops-platform

      # Upload generated Helm repo as Pages artifact
      - name: Uploadartifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: helm/docs

      # Deploy to GitHub Pages
      - name: DeploytoGitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
